backup/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^fer_backups/$', views.fer_backups, name='fer_backups'),
]

miniprojecte/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = (
[
    url(r'^', include('usuaris.urls' , namespace='usuaris')),
    url(r'^videos/', include('videos.urls')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^', include('backup.urls', namespace='backup')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

usuaris/urls.py
from django.conf.urls import url, include
from usuaris import views

app_name = 'usuaris'

urlpatterns = [
    # ex: /practicaMonoPoli/...
    #url(r'^create/', views.Afegir_Modificar_Jugador, name='Afegir_Jugador'),
    #url(r'^modify/(?P<jugador_id>\d+)/$', views.Afegir_Modificar_Jugador, name='Modificar_Jugador'),
    #url(r'^eliminar/(?P<jugador_id>[0-9]+)/$',views.Eliminar_Jugador, name="Eliminar_Jugador"),
    #url(r'^llista/$', views.llista_jugadors, name='llista_jugadors'),
    url(r'^login/$', views.login, name="login", ),
    url(r'^logout/$', views.logout, name="logout", ),
    url(r'^registre/$', views.registrar, name="registre"),
    url(r'^$', views.index, name="index"),
]

videos/urls.py
from django.conf.urls import url , include
from videos import views
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static


app_name = 'videos'


urlpatterns = patterns('',

    url( r'upload/', views.upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', views.upload_delete, name = 'jfu_delete' ),
    url(r'^llistavideos/$', views.llista_videos, name="llista_videos"),
)

videos/models.py
from __future__ import unicode_literals
from django.core.validators import MaxValueValidator
from django import forms
from django.db.models import FileField
from django.forms import forms
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


from django.db import models
#from django.contrib import admin
#from my_awesome_app.models import MyAwesomeModelWithFiles


class ContentTypeRestrictedFileField(models.FileField):

    def __init__(self, content_types=None,max_upload_size=859832320, **kwargs):
        self.content_types = kwargs.pop('video/avi' , 'video/mp4')
        self.max_upload_size = max_upload_size

        super(ContentTypeRestrictedFileField, self).__init__(**kwargs)

    def clean(self, *args, **kwargs):
        data = super(ContentTypeRestrictedFileField, self).clean(*args, **kwargs)

        file = data.file
        try:
            content_type = file.content_type
            if content_type in self.content_types:
                if file._size > self.max_upload_size:
                    raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(self.max_upload_size), filesizeformat(file._size)))
            else:
                raise forms.ValidationError(_('Filetype not supported.'))
        except AttributeError:
            pass

        return data


class Video(models.Model):
    titol = models.CharField(max_length=100 , blank=False,unique=True,help_text="Titul del video.")
    tamany = models.IntegerField(help_text="Tamany del video.")
    tipus = models.CharField(max_length=5,blank=False)
    data = models.DateField(auto_now_add=True, help_text="Data del video pujat.")
    video = models.FileField(upload_to='.',help_text="Video per pujar",blank=False )
    usuari = models.ForeignKey(User)

    def __unicode__(self):
        return u'%s' % (self.titol)

videos/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from videos.models import Video
from django.contrib import messages
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
import os
from django.conf import settings
from django.core.urlresolvers import reverse
from django.views import generic
from django.views.decorators.http import require_POST
from jfu.http import upload_receive, UploadResponse, JFUResponse



@login_required
def llista_videos(request):
    videos = (Video.objects.order_by("nom"))
    paginacion = Paginator(videos, 30)
    page = request.GET.get('page')


    try:
        videos = paginacion.page(page)
    except PageNotAnInteger:
        videos = paginacion.page(1)
    except EmptyPage:
        videos = paginacion.page(paginacion.num_pages)
    ctx = {
        'videos': videos
    }

    return render(request, 'llista_videos.html', ctx)



class Home( generic.TemplateView ):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super( Home, self ).get_context_data( **kwargs )
        context['accepted_mime_types'] = ['image/*']
        return context

@require_POST
def upload( request ):
    video = upload_receive( request )

    instance = Video( video = video )
    instance.save()

    basename = os.path.basename( instance.video.path )
    
    file_dict = {
        'name' : basename,
        'size' : video.size,

        'url': settings.MEDIA_URL + basename,
        'thumbnailUrl': settings.MEDIA_URL + basename,

        'deleteUrl': reverse('jfu_delete', kwargs = { 'pk': instance.pk }),
        'deleteType': 'POST',
    }

    return UploadResponse( request, file_dict )

@require_POST
def upload_delete( request, pk ):
    success = True
    try:
        instance = Video.objects.get( pk = pk )
        os.unlink( instance.video.path )
        instance.delete()
    except Video.DoesNotExist:
        success = False

    return JFUResponse( request, success )
 

videos/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block title %} StreamLoad {% endblock %}</title>

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static "css/estils.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
  <!-- Bootstrap -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">





  {% block extra-head %} {% endblock %}

</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
        <a class="navbar-brand" href="{% url "videos:llista_videos" %}">StreamLoad</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}{% ifequal user.username "admin" %}
          
          <a href="{% url 'backup:fer_backups' %}"><span class="glyphicon glyphicon-hdd"></span> Backup</a> {% endifequal %}
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span style="color:{{user}};">{{user}} </span>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Canvi password</a></li>
              <li><a href="#">Les meves dades del perfil</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url "usuaris:logout" %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sing Up/Login <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url "usuaris:registre" %}">Sing Up</a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href="{% url "usuaris:login" %}">Login</a>
                </li>
                <li>
                  <a href="{% url "social:begin" "google-oauth2" %}">Google+</a>
                  <a href="{% url "social:begin" "twitter" %}">Twitter</a>
                </li>
              </ul>
            </li>
          </ul>
          {% endif %}
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
  <div>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </ul>
    {% endif %} {% block content %} {% endblock %}
  </div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  

  {% block extra-script %} {% endblock %}
</body>

</html>

videos/templates/eliminar_video.html
{% extends "base.html" %}

{% block content %}
    <a href=""></a>
    <form action="" method="post" class="container">
        {% csrf_token %}
        <h4>Segur que vols esborrar el video <strong>{{ video.nom }}</strong> ?</h4>
        <input type="submit" class="btn btn-danger btn-lg" value="Borrar"/>
        <button type="button" class="btn btn-default btn-lg"><a href="../../llista_videos.html">Cancelar</a></button>
    </form>
{% endblock %}

videos/templates/llista_videos.html
{% extends 'base.html' %}{% block title %}StreamLoad{% endblock %}{% block extra-head %}
{% endblock %}
{% block content %} {% if user.is_authenticated %}
<html>

<head>

</head>

<body>
    <div id="contenedor">
              {% load jfutags %} 
                {% jfu 'photo_upload_form.html' 'videos:jfu_upload'%}
        <div id="carpeta">
            <span>carpeta 1</span>
    
        </div>
        
        <div id="table" class="table-responsive panel panel-primary">
            <table>
                <tr class="text-center">
                    <td>TITOL</td>
                    <td>TAMANY</td>
                    <td>FORMATO</td>
                    <td>DATA</td>
                    <td>Video Download</td>
                    <td>Video Preview</td>
                    <td>Eliminar</td>
                </tr>
            </table>
            <table id="taula" class="table-responsive">
                <tbody>
    
                    {% for video in video_list %}
                    <tr class="text-center">
                        <td>{{video.titol}}</td>
                        <td>{{video.tamany}} BYTE</td>
                        <td>{{video.formato}}</td>
                        <td>{{video.data}}</td>
                        <td>
                            <a href="{{video.video.url}}" download>DOWNLOAD</a>
                        </td>
                        <td>
                            <a href="{{video.video.url}}">PREVIEW</a>
                        </td>
                        <td>
                            <a class="btn btn-danger" href="{% url 'videos:eliminarvideo' video.pk %}"><span></span>Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <ul class="pagination">
                        {% if video_list.has_previous %}
                            <li><a href="?page={{ video_list.previous_page_number }}">«</a></li>
                        {% else %}
                            <li class="disabled"><a href="#">«</a></li>
                        {% endif %} 
                        
                        {% for page in video_list.paginator.page_range %}
                        <li class="
                            {% if video_list.number == page  %}
                                active
                            {% endif %}">
                                <a href="?page={{page}}">{{ page }}</a></li>
                        {% endfor %} 
                        
                        {% if video_list.has_next %}
                        <li><a href="?page={{ video_list.next_page_number }}">»</a></li>
                        {% else %}
                            <li class="disabled"><a href="#">»</a></li>
                        {% endif %}
                    </ul>
                </tbody>
            </table>
        </div>
    </div>    
</body>

</html>

{% endif %} {% endblock %}

videos/templates/photo_upload_form.html
{% extends 'jfu/upload_form.html' %}

{% block JS_OPTS %}
sequentialUploads: true,
acceptFileTypes: /(\.|\/)(avi|mp4|mkv?g)$/i
{% endblock %}